### ISSUE TITLE
Generator Row is not working as expected

### ISSUE THREAD

**Issue by rahul-yr** [mjafartp/flutter_esc_pos_utils#25]
Below is the code I have used.

```
 bytes += generator.row([
    PosColumn(
      text: 'Some text 1 + Some text 2',
      width: 3,
      styles: const PosStyles(align: PosAlign.left),
    ),
    PosColumn(
      text: '100',
      width: 6,
      styles: const PosStyles(align: PosAlign.center),
    ),
    PosColumn(
      text: '10000',
      width: 3,
      styles: const PosStyles(align: PosAlign.right),
    ),
  ]);

```

And this is the exception 

```
E/flutter (22676): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Only one parameter - text or textEncoded - should be passed
E/flutter (22676): #0      new PosColumn (package:flutter_esc_pos_utils/src/pos_column.dart:19:7)
E/flutter (22676): #1      Generator.row (package:flutter_esc_pos_utils/src/generator.dart:502:25)
E/flutter (22676): #2      fetchPrintData (package:ble_ff/esc_pos.dart:43:22)
E/flutter (22676): <asynchronous suspension>
E/flutter (22676): #3      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (package:ble_ff/my_home_page.dart:137:40)
E/flutter (22676): <asynchronous suspension>
E/flutter (22676): 
```

Please share your thoughts on this asap.

**Comment by ionLuca23** [comment]
Hi. I want to confirm the issue. I think the issue is related to  PosColumn() constructor. If textEncoded not null we always get an Exception.

**Comment by E-MRE** [comment]
I found this code inside of the PosColumn:

```
if (text.isEmpty && textEncoded != null && textEncoded!.isNotEmpty) {
      throw Exception(
          'Only one parameter - text or textEncoded - should be passed');
 }
```

And generator doesn't set text variable. For this reason pos column throws exception.

**Comment by naingolan** [comment]
The answer is to add multiline:false after writing the posColumn array   ,  

bytes += generator.row([
    PosColumn(
      text: 'Some text 1 + Some text 2',
      width: 3,
      styles: const PosStyles(align: PosAlign.left),
    ),
    PosColumn(
      text: '100',
      width: 6,
      styles: const PosStyles(align: PosAlign.center),
    ),
    PosColumn(
      text: '10000',
      width: 3,
      styles: const PosStyles(align: PosAlign.right),
    ),
  ], multiLine:false);

**Comment by sky007Xyz** [comment]
https://pub.dev/packages/esc_pos_utils

use this package

**Comment by SidouAbr** [comment]
> The answer is to add multiline:false after writing the posColumn array ,
> 
> bytes += generator.row([ PosColumn( text: 'Some text 1 + Some text 2', width: 3, styles: const PosStyles(align: PosAlign.left), ), PosColumn( text: '100', width: 6, styles: const PosStyles(align: PosAlign.center), ), PosColumn( text: '10000', width: 3, styles: const PosStyles(align: PosAlign.right), ), ], multiLine:false);

Its work for me, but it need to limit the legnth String
